import { useEffect, useState } from 'react'

/**
 * "On this page" navigation for long-form articles.
 *
 * Headings come from the post's own markdown (see extractHeadings), and their
 * ids are generated by the same slugifier the renderer uses, so links and
 * anchors cannot drift apart.
 *
 * Behaviour:
 *  - sticky alongside the article on wide screens
 *  - collapses into a <details> above the article on narrow ones
 *  - highlights the section currently in view
 *  - renders nothing when there are too few headings to be worth it
 */
export default function TableOfContents({ headings, minHeadings = 3 }) {
  const [activeId, setActiveId] = useState('')

  useEffect(() => {
    if (!headings?.length) return

    const elements = headings
      .map((h) => document.getElementById(h.id))
      .filter(Boolean)
    if (!elements.length) return

    // Track which headings are above the fold line; the last one past it is
    // the section being read. More stable than "first intersecting", which
    // flickers when several headings share a viewport.
    const seen = new Map()
    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) seen.set(entry.target.id, entry)

        const passed = elements
          .filter((el) => {
            const e = seen.get(el.id)
            return e && e.boundingClientRect.top < 120
          })
          .map((el) => el.id)

        if (passed.length) {
          setActiveId(passed[passed.length - 1])
        } else {
          const firstVisible = elements.find((el) => seen.get(el.id)?.isIntersecting)
          setActiveId(firstVisible ? firstVisible.id : elements[0].id)
        }
      },
      { rootMargin: '-100px 0px -60% 0px', threshold: [0, 1] }
    )

    elements.forEach((el) => observer.observe(el))
    return () => observer.disconnect()
  }, [headings])

  if (!headings || headings.length < minHeadings) return null

  const list = (
    <ol className="toc__list">
      {headings.map((h) => (
        <li
          key={h.id}
          className={`toc__item toc__item--h${h.depth}${
            activeId === h.id ? ' is-active' : ''
          }`}
        >
          <a
            href={`#${h.id}`}
            className="toc__link"
            aria-current={activeId === h.id ? 'true' : undefined}
          >
            {h.text}
          </a>
        </li>
      ))}
    </ol>
  )

  return (
    <>
      {/* Wide screens: sticky rail */}
      <nav className="toc toc--rail" aria-labelledby="toc-heading">
        <h2 className="toc__title" id="toc-heading">On this page</h2>
        {list}
      </nav>

      {/* Narrow screens: collapsed by default so it never pushes the article down */}
      <details className="toc toc--collapsible">
        <summary className="toc__summary">
          <span className="toc__title">On this page</span>
          <svg width="18" height="18" viewBox="0 0 20 20" fill="none" aria-hidden="true">
            <path
              d="M5 8 L10 13 L15 8"
              stroke="currentColor"
              strokeWidth="1.75"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </summary>
        {list}
      </details>
    </>
  )
}
